language: node_js
node_js:
  - "8"
  - "10"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
env:
  - SNYK_TOKEN=3c0de5da-b07d-47d3-ab44-880d35a096e3
install:
  - npm install
script:
  - npm install codecov -g
  - npm install snyk -g
  - npm test
  - npm run build
after_success:
  - cat ./coverage/coverage.lcov | codecov
