language: node_js
node_js:
  - "8"
  - "10"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm install codecov -g
  - npm install snyk -g
  - npm test
  - npm run build
  - snyk wizard
  - snyk monitor
after_success:
  - cat ./coverage/coverage.lcov | codecov
