language: node_js
node_js:
  - "8"
  - "10"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm install codecov -g
  - npm test
  - npm run lint
after_success:
  - codecov